---
- name: init conf dir
  file: path=~/.config state=directory

- name: download commander
  get_url:
    url: https://github.com/Fedomn/c/raw/master/release/c.linux
    dest: ~/.config
    mode: '0755'
    force: yes

- name: copy over .c.config
  template:
    src: ".c.conf.j2"
    dest: "~/.config/.c.conf"

- name: enable alias
  lineinfile: dest="~/.bashrc" state=present line={{ item }}
  with_items:
    - alias c="~/.config/c.linux"
